### ISSUE TITLE
Publish to the market place

### ISSUE THREAD

**Issue by lazka** [msys2/setup-msys2#37]
So that the action is more visible.

* What do we need for this?
* And what should we do about https://github.com/marketplace/actions/setup-msys2-environment ?

**Comment by eine** [comment]
According to https://help.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace, some of us needs to accept the https://help.github.com/en/github/site-policy/github-marketplace-developer-agreement (I don't know how to do that). Then, we'd need to change the name https://github.com/msys2/setup-msys2/blob/master/action.yml#L1, because it cannot conflict with the existing one. However, I don't know if the system will allow us to do it anyway. I mean, there should be a banner suggesting us to publish it, and there is not. Maybe it is still identified as a fork, although not shown above. Maybe you can ask through the same channel you used to request the removal of the "fork from"?

OTOH, I don't think it's possible to change the existing one for it to point here. Hence, we should politely ask for it to be removed, or just let both of them coexist.

**Comment by lazka** [comment]
OK, maybw @Ecco knows more.

**Comment by lazka** [comment]
@Ecco care to have a look? If you don't have time that's OK, but please tell us :)

**Comment by lazka** [comment]
I've filed https://github.com/numworks/setup-msys2/issues/37

**Comment by lazka** [comment]
Next steps as discussed on gitter:

* Prepare this repo to be publishable (fix naming, maybe add icon/color thing as suggested by github?)
* Create a new MSYS2 installer release while we are at it
* Publish to the market place

**Comment by eine** [comment]
This Action is now published in the marketplace: https://github.com/marketplace/actions/setup-msys2

The released version is tag v2 (https://github.com/msys2/setup-msys2/releases). Hopefully, it will allow us to have that tag updated to the latest v2.x.x branch.
