### ISSUE TITLE
Streamlining matrix builds

### ISSUE THREAD

**Issue by newhoggy** [msys2/setup-msys2#71]
I'm interested in streamlining matrix builds that include Linux and MacOS.

Currently, `msys2/setup-msys2` fails on non-Windows platforms.  It would be nice if there was an option to not fail and instead do nothing.  This would mean I don't have to conditionally perform the installation.

Additionally, having an extra `msys2do` shell command which internally runs `msys2 -c <cmd>` on Windows and runs `<cmd>` directly everywhere else also helps.

**Comment by eine** [comment]
Hi @newhoggy! I think it's ok not to fail on non-Windows platforms but display a warning instead.

With regard to `msysdo`, unfortunately it is not possible to have the same file behave differently, because it's a `cmd` file. The non-Windows execution would need to create a different file. Instead, I think that an `alias msys2=bash` should be created. Either `shell: bash {0}` or `run: bash -c 'uname -a'` are valid commands.

Do you want to give it a try?

**Comment by newhoggy** [comment]
Is there a way to make `alias msys2=bash` persist between jobs?  The commands I want to run under `msys2` are scattered amongst multiple jobs?

**Comment by eine** [comment]
Note that currently setup-msys2 is not persistent between jobs. It works for multiple steps, but it needs to be executed in each job.

From a technical point of view, rather than an alias, you might want to symlink e.g. `/usr/bin/msys2` to `/usr/bin/bash`. That's actually the "interesting" issue of this feature: finding the solution that is preserved properly.

For using msys2 in multiple step, set it as a global shell. See https://github.com/msys2/setup-msys2#usage

**Comment by eine** [comment]
Option `platform-check-severity` as added in v2.6.0. See #172 and https://github.com/msys2/setup-msys2/blob/master/CHANGELOG.md#260---20211103.
