### ISSUE TITLE
Add to path without inherit?

### ISSUE THREAD

**Issue by 3b** [msys2/setup-msys2#72]
I'd like to add a few directories to the path, but still keep `minimal` or `strict` `path-type` so I don't get confused by tools from other sources.

Ideally, it would just detect the existing `::add-path::/foo` entries that are also seen by bash on linux/mac, so I only need to add it in one place, but an extra `add-path: '/foo:~/bar'` or similar option to the `setup-msys2` action would probably also work for my current uses (though possibly would require hard-coding some paths unless I can get access to env vars there for $HOME or similar).

**Comment by eine** [comment]
I'm not sure to understand the use case. It feels like something you could add to `.bashrc` in a single step, after this action. Furthermore, you might execute that setup step only with `MSYS2_PATH_TYPE=inherit`, so you get access to all the envvars when setting up your custom paths.

Would you mind providing an example workflow where this feature would be used?

**Comment by 3b** [comment]
Yeah, dumping things in `.bashrc` is probably the best workaround, and probably as good as an extra option to the action. just hoped to keep using existing code (with `::add-path::`) if possible.

Running only one step with `inherit` is also an interesting suggestion, hadn't though of that. 

https://github.com/3b/pngload/blob/ci/.github/workflows/test.yml is the workflow that inspired it. Switching to using `.bashrc` instead of `::add-path::` wouldn't be a big change, so I might just switch to that.

**Comment by eine** [comment]
In the reference workflow you linked, there is already an specific step for customizing the PATH on Windows. Hence, as you say, the change would be very small. Moreover, I believe it more "idiomatic" to avoid `inherit` as a default setting and, instead, add the custom locations to MSYS2's internal PATH rather than to the Windows PATH.

Should you need to have some custom locations added both in MSYS2 and on the Windows PATH, I'd suggest using `::add-path::` and `.bashrc` at the same time.

**Comment by eine** [comment]
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by eine** [comment]
See https://github.com/umarcor/Surelog/blob/bec95782d6e44cbee8c7f4ce87c6e58716ddd0da/.github/workflows/test.yml#L89-L91 for and example about how to add a path to bashrc.
